export enum EstadoEquipos {
    DISPONIBLE = "DISPONIBLE",
    DISPONIBLE_CON_DETALLES = "DISPONIBLE_CON_DETALLES",
    EN_TALLER = "EN_TALLER",
    EN_VIAJE = "EN_VIAJE",
    FUERA_DE_SERVICIO = "FUERA_DE_SERVICIO",
}