export const tipoServicio = [
    { key: "RELLENO DE ACEITE", value: "RELLENO DE ACEITE" },
    { key: "RELLENO DE ACEITE Y ANTICONGELANTE", value: "RELLENO DE ACEITE Y ANTICONGELANTE" },
    { key: "RELLENO DE AD BLUE", value: "RELLENO DE AD BLUE" },
    { key: "RELLENO DE AD BLUE Y CAMBIO DE ACEITE", value: "RELLENO DE AD BLUE Y CAMBIO DE ACEITE" },
    { key: "RELLENO DE ANTICONGELANTE", value: "RELLENO DE ANTICONGELANTE" },
    { key: "RELLENO DE ANTICONGELANTE Y ATF", value: "RELLENO DE ANTICONGELANTE Y ATF" },
    { key: "RELLENO DE ANTICONGELANTE Y ACEITE", value: "RELLENO DE ANTICONGELANTE Y ACEITE" },
    { key: "SERVICIO TIPO A", value: "SERVICIO TIPO A" },
    { key: "SERVICIO TIPO B", value: "SERVICIO TIPO B" },
];